In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# 1) Feather 로드 ----------------------------------------------------------
feat_path = Path("data/feature_store/daily_features.feather")
df = pd.read_feather(feat_path)

In [6]:
df[df['inventory_est']>0].describe()

,date,spot_id,total_rev_log1p,dow,week,month,quarter,is_weekend,offday_run,lag_1,...,land_price_log,region_total_rev,region_vehicle_count,region_rev_per_vehicle,region_code,doy_sin,doy_cos,month_sin,month_cos,region_vehicle_mean_rev
count,1642588,1.642588e+06,1.642588e+06,1.642588e+06,1642588.0,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06,...,1.635404e+06,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06,1.642588e+06
mean,2024-02-19 06:35:50.126994432,2.284057e+03,5.210536e+00,3.004015e+00,28.227708,6.934346e+00,2.639476e+00,2.871402e-01,1.000571e+04,3.472942e+04,...,1.491054e+01,1.771583e+07,3.097306e+02,5.454262e+04,1.218422e+02,-7.891097e-02,-1.483539e-03,-7.861601e-02,-2.684248e-02,1.062659e+00
min,2023-01-06 00:00:00,1.000000e+00,0.000000e+00,0.000000e+00,1.0,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.216622e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.080000e+02,-9.999907e-01,-9.999630e-01,-1.000000e+00,-1.000000e+00,5.419288e-05
25%,2023-09-13 00:00:00,1.626000e+03,0.000000e+00,1.000000e+00,16.0,4.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.420850e+01,6.910796e+06,1.210000e+02,4.599428e+04,1.080000e+02,-7.748840e-01,-6.963762e-01,-8.660254e-01,-8.660254e-01,4.945050e-01
50%,2024-03-10 00:00:00,2.127000e+03,0.000000e+00,3.000000e+00,30.0,7.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.492240e+01,1.522155e+07,3.180000e+02,5.132790e+04,1.190000e+02,-1.797666e-01,-1.291030e-02,0.000000e+00,-1.836970e-16,7.085568e-01
75%,2024-08-12 00:00:00,3.408000e+03,1.092172e+01,5.000000e+00,41.0,1.000000e+01,4.000000e+00,1.000000e+00,6.787000e+03,5.526500e+04,...,1.550179e+01,2.422097e+07,4.400000e+02,6.305748e+04,1.310000e+02,6.420547e-01,6.901734e-01,5.000000e-01,5.000000e-01,1.530016e+00
max,2024-12-31 00:00:00,4.390000e+03,1.434326e+01,6.000000e+00,52.0,1.200000e+01,4.000000e+00,1.000000e+00,1.993190e+05,1.695116e+06,...,1.829829e+01,8.754635e+07,9.990000e+02,1.045698e+05,2.390000e+02,9.999907e-01,1.000000e+00,1.000000e+00,1.000000e+00,3.693576e+00
std,NaN,1.101308e+03,5.465520e+00,2.003338e+00,14.870734,3.404490e+00,1.106506e+00,4.524277e-01,2.071675e+04,5.656213e+04,...,9.808049e-01,1.327607e+07,1.866243e+02,1.131454e+04,1.850049e+01,7.101731e-01,6.995896e-01,7.121036e-01,6.971428e-01,8.330785e-01

In [13]:
len(df[(df['total_rev_log1p']==0) & (df['inventory_est']>0)])

855814

In [6]:
len(df['total_rev_log1p'])

25712016

In [10]:
len(df[df['inventory_est']>0])

1642588